#!/bin/sh
set -e

DEB_FILE="/tmp/oscript.deb"
RELEASES_URL="https://github.com/EvilBeaver/OneScript/releases"
test -z "$TMPDIR" && TMPDIR="$(mktemp -d)"

last_version() {
  curl -sL -o /dev/null -w %{url_effective} "$RELEASES_URL/latest" | 
    rev | 
    cut -f1 -d'/'| 
    rev
}

download() {
  test -z "$VERSION" && VERSION="$(last_version)"
  test -z "$VERSION" && {
    echo "Unable to get goreleaser version." >&2
    exit 1
  }
  rm -f "$DEB_FILE"
  curl -s -L -o "$DEB_FILE" \
    "$RELEASES_URL/download/$VERSION/OneScript_$(uname -s)_all.deb"
}

download

dpkg -i "$DEB_FILE"

oscript -v
